{% set name = "kineticstoolkit" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kineticstoolkit-{{ version }}.tar.gz
  sha256: 0af5c12bfa7fd8ab32d6dce1e5ef3495e231cc99d7e0adcc3ff46833df0a5e82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - pandas
    - pyqt
    - python >=3.8
    - scikit-learn
    - scipy
    - tqdm
    - limitedinteraction
    - ezc3d
    - requests-cache

test:
  imports:
    - kineticstoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://kineticstoolkit.uqam.ca
  summary: An open-source python library to facilitate research in biomechanics.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - felixchenier
