{% set name = "kineticstoolkit" %}
{% set version = "0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kineticstoolkit-{{ version }}.tar.gz
  sha256: 42b21d0423185fc62d88793117551610f230a2c4b8f4431e620c5dc58a5569e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - pandas
    - pyqt
    - python >=3.8
    - scikit-learn
    - scipy
    - requests
    - limitedinteraction
    - ffmpeg
    - ffmpeg-python

test:
  imports:
    - kineticstoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://felixchenier.uqam.ca/kineticstoolkit
  summary: An open-source python library to facilitate research in biomechanics.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - felixchenier
